apiVersion: apps/v1
kind: Deployment
metadata:
    # Nome do deployment
    name: {{ .Values.release.name}}
# Especificação do pod
spec:
    replicas: {{ .Values.release.replicaCount}}
    selector:
        matchLabels:
            app: {{ .Values.release.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.release.name }}
        spec:
            containers:
              - name: {{ .Values.release.name }}
                image: {{ .Values.release.image }}
                ports:
                - containerPort: {{ .Values.release.port}}
                env:
                - name: PORT
                  value: {{ .Values.release.port | quote}}