apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: apm-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "cert-manager-config"
spec:
  tls:
  - hosts:
    - apm.devopstests.com
    secretName: apm-tls
  rules:
  - host: apm.devopstests.com
    http:
      paths:
      - backend:
          serviceName: {{ .Values.release.name }}
          servicePort: {{ .Values.release.port }}